import React from 'react';
import '@fortawesome/fontawesome-free/css/all.min.css';

export const dashboard = <i className="fas fa-chart-line"></i>;
export const edit = <i class="fa-regular fa-pen-to-square"></i>
export const transactions = <i className="fas fa-credit-card"></i>;
export const categories = <i className="fas fa-tags"></i>;
export const accounts = <i className="fas fa-wallet"></i>;
export const hamMenu = <i class="fa-solid fa-bars"></i>;
export const settings = <i className="fas fa-cog"></i>;
export const logout = <i className="fas fa-sign-out-alt"></i>;
export const trend = <i className="fas fa-money-bill-trend-up"></i>;
export const expenses = <i className="fas fa-money-bill-transfer"></i>;
export const money = <i className="fas fa-money-bill"></i>;
export const freelance = <i className="fas fa-earth-americas"></i>;
export const stocks = <i className="fas fa-arrow-trend-up"></i>;
export const bitcoin = <i className="fab fa-bitcoin"></i>;
export const piggy = <i className="fas fa-piggy-bank"></i>;
export const yt = <i className="fab fa-youtube"></i>;
export const card = <i className="fab fa-cc-visa"></i>;
export const users = <i className="fas fa-users-between-lines"></i>;
export const dollar = <i className="fas fa-dollar-sign"></i>;
export const calender = <i className="fas fa-calendar"></i>;
export const comment = <i className="fas fa-comment"></i>;
export const plus = <i className="fas fa-plus"></i>;
export const trash = <i className="fas fa-trash"></i>;
export const signout = <i className="fas fa-sign-out-alt"></i>;
export const takeaway = <i className="fas fa-utensils"></i>;
export const clothing = <i className="fas fa-shirt"></i>;
export const book = <i className="fas fa-book-open"></i>;
export const food = <i className="fas fa-bowl-food"></i>;
export const medical = <i className="fas fa-briefcase-medical"></i>;
export const tv = <i className="fas fa-tv"></i>;
export const circle = <i className="fas fa-circle-dot"></i>;
